services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "TopSec1!"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  auth:
    build:
      context: .
      dockerfile: ./MSChat.Auth/Dockerfile
    container_name: auth
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mssql
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      OrchardCore__DatabaseProvider: SqlConnection
      OrchardCore__ConnectionString: Server=mssql;Encrypt=true;TrustServerCertificate=true;MultipleActiveResultSets=true;User Id=sa;Password=TopSec1!
      OrchardCore__OrchardCore_Shells_Database__DatabaseProvider: SqlConnection
      OrchardCore__OrchardCore_Shells_Database__ConnectionString: Server=mssql;Encrypt=true;TrustServerCertificate=true;MultipleActiveResultSets=true;User Id=sa;Password=TopSec1!
      OrchardCore__OrchardCore_Shells_Database__TablePrefix: sc
      OrchardCore__OrchardCore_Shells_Database__MigrateFromFiles: true

volumes:
  mssql_data:
