services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "TopSec1!"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
      - "9002:8001"

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  
  auth:
    build:
      context: .
      dockerfile: ./MSChat.Auth/Dockerfile
    container_name: auth
    ports:
      - "5000:8080"
      - "5001:8081"

  webapp:
    build:
      context: .
      dockerfile: ./MSChat.WebBFF/Dockerfile
    container_name: webapp
    ports:
      - "5002:8080"
      - "5003:8081"
    depends_on:
      - auth
    environment:
      - WebClient__OidcServerUri=http://localhost:5000
      - WebClient__OidcClientId=mschat.webclient
      - WebClient__ChatApiUri=http://localhost:5004
      - WebClient__PresenceApiUri=http://localhost:5006
      
  chatapi:
    build:
      context: .
      dockerfile: ./MSChat.ChatAPI/Dockerfile
    container_name: chatapi
    ports:
      - "5004:8080"
      - "5005:8081"
    depends_on:
      - auth
      - mssql
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ChatDBConnection=Server=mssql;Database=MSChat.Chat;User Id=sa;Password=TopSec1!;Encrypt=True;TrustServerCertificate=True;
      - ApiAuth__Authority=http://auth:8080
      - ApiAuth__ValidIssuer=http://localhost:5000/
      - Cors__AllowedOrigins=https://localhost:5100,https://localhost:5003,http://localhost:5002
      - Redis__ConnectionString=redis:6379

  presenceapi:
    build:
      context: .
      dockerfile: ./MSChat.PresenceAPI/Dockerfile
    container_name: presenceapi
    ports:
      - "5006:8080"
      - "5007:8081"
    depends_on:
      - auth
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiAuth__Authority=http://auth:8080
      - ApiAuth__ValidIssuer=http://localhost:5000/
      - Cors__AllowedOrigins=https://localhost:5100,https://localhost:5003,http://localhost:5002
      - Redis__ConnectionString=redis:6379

volumes:
  mssql_data:
  rabbitmq_data:
  